# Generated by Django 3.0.5 on 2020-07-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='suscribe',
        ),
    ]
