# Generated by Django 3.0.5 on 2020-08-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0005_auto_20200805_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
