# Generated by Django 3.0.5 on 2020-08-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0007_auto_20200805_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
