# Generated by Django 3.0.5 on 2020-08-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='cateii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(max_length=50)),
            ],
        ),
    ]
