# Generated by Django 3.0.5 on 2020-08-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0009_cateii'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cateii',
        ),
        migrations.AddField(
            model_name='post',
            name='cate',
            field=models.CharField(choices=[('education', 'education')], default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
